<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateModelsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('models', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title');
            $table->integer('brand_id');
            $table->integer('active')->default(1);
            $table->timestamps();
        });
        DB::table('models')->insert(array(
            array('title' => '4RUNNER','brand_id'=>1,'active'=>1),
            array('title' => '86GT','brand_id'=>1,'active'=>1),
            array('title' => 'ALPHARD','brand_id'=>1,'active'=>1),
            array('title' => 'ALTEZZA','brand_id'=>1,'active'=>1),
            array('title' => 'ALTIS','brand_id'=>1,'active'=>1),
            array('title' => 'ARISTO','brand_id'=>1,'active'=>1),
            array('title' => 'AVANZA','brand_id'=>1,'active'=>1),
            array('title' => 'BB','brand_id'=>1,'active'=>1),
            array('title' => 'CALDINA','brand_id'=>1,'active'=>1),
            array('title' => 'CAMRY','brand_id'=>1,'active'=>1),
            array('title' => 'CARIB','brand_id'=>1,'active'=>1),
            array('title' => 'CARINA','brand_id'=>1,'active'=>1),
            array('title' => 'CAVALIER','brand_id'=>1,'active'=>1),
            array('title' => 'CELICA','brand_id'=>1,'active'=>1),
            array('title' => 'CENTURY','brand_id'=>1,'active'=>1),
            array('title' => 'COMMUTER','brand_id'=>1,'active'=>1),
            array('title' => 'COROLLA','brand_id'=>1,'active'=>1),
            array('title' => 'CORONA','brand_id'=>1,'active'=>1),
            array('title' => 'CRESSIDA','brand_id'=>1,'active'=>1),
            array('title' => 'CROWN','brand_id'=>1,'active'=>1),
            array('title' => 'DYNA','brand_id'=>1,'active'=>1),
            array('title' => 'EMINA','brand_id'=>1,'active'=>1),
            array('title' => 'ESQUIRE','brand_id'=>1,'active'=>1),
            array('title' => 'ESTIMA','brand_id'=>1,'active'=>1),
            array('title' => 'FORTUNER','brand_id'=>1,'active'=>1),
            array('title' => 'GAIA','brand_id'=>1,'active'=>1),
            array('title' => 'GLANZA','brand_id'=>1,'active'=>1),
            array('title' => 'GRAND HIACE','brand_id'=>1,'active'=>1),
            array('title' => 'GRANVIA','brand_id'=>1,'active'=>1),
            array('title' => 'HARRIER','brand_id'=>1,'active'=>1),
            array('title' => 'HIACE','brand_id'=>1,'active'=>1),
            array('title' => 'HILUX HERO','brand_id'=>1,'active'=>1),
            array('title' => 'HILUX MIGHTY-X','brand_id'=>1,'active'=>1),
            array('title' => 'HILUX SPORT RIDER','brand_id'=>1,'active'=>1),
            array('title' => 'HILUX TIGER','brand_id'=>1,'active'=>1),
            array('title' => 'HILUX TIGER D4D','brand_id'=>1,'active'=>1),
            array('title' => 'HILUX VIGO','brand_id'=>1,'active'=>1),
            array('title' => 'HILUX VIGO D4D','brand_id'=>1,'active'=>1),
            array('title' => 'INNOVA','brand_id'=>1,'active'=>1),
            array('title' => 'IPSUM','brand_id'=>1,'active'=>1),
            array('title' => 'IQ','brand_id'=>1,'active'=>1),
            array('title' => 'IST','brand_id'=>1,'active'=>1),
            array('title' => 'KLUGER','brand_id'=>1,'active'=>1),
            array('title' => 'LAND CRUISER','brand_id'=>1,'active'=>1),
            array('title' => 'Landcruiser Prado','brand_id'=>1,'active'=>1),
            array('title' => 'LEVIN','brand_id'=>1,'active'=>1),
            array('title' => 'LIACE','brand_id'=>1,'active'=>1),
            array('title' => 'LITEAC','brand_id'=>1,'active'=>1),
            array('title' => 'LN','brand_id'=>1,'active'=>1),
            array('title' => 'LUCIDA','brand_id'=>1,'active'=>1),
            array('title' => 'MARINO','brand_id'=>1,'active'=>1),
            array('title' => 'MARK II','brand_id'=>1,'active'=>1),
            array('title' => 'MARK X','brand_id'=>1,'active'=>1),
            array('title' => 'MR-S','brand_id'=>1,'active'=>1),
            array('title' => 'MR2','brand_id'=>1,'active'=>1),
            array('title' => 'NOAH','brand_id'=>1,'active'=>1),
            array('title' => 'PASEO','brand_id'=>1,'active'=>1),
            array('title' => 'PORTE','brand_id'=>1,'active'=>1),
            array('title' => 'PREVIA','brand_id'=>1,'active'=>1),
            array('title' => 'PRIUS','brand_id'=>1,'active'=>1),
            array('title' => 'AV 4','brand_id'=>1,'active'=>1),
            array('title' => 'REGIUS','brand_id'=>1,'active'=>1),
            array('title' => 'SERA','brand_id'=>1,'active'=>1),
            array('title' => 'SIENNA','brand_id'=>1,'active'=>1),
            array('title' => 'SOARER','brand_id'=>1,'active'=>1),
            array('title' => 'SOLUNA','brand_id'=>1,'active'=>1),
            array('title' => 'SPACIO','brand_id'=>1,'active'=>1),
            array('title' => 'SPORT CRUISER','brand_id'=>1,'active'=>1),
            array('title' => 'SPORT RIDER','brand_id'=>1,'active'=>1),
            array('title' => 'SR5','brand_id'=>1,'active'=>1),
            array('title' => 'STARLET','brand_id'=>1,'active'=>1),
            array('title' => 'SUPER CUSTOM','brand_id'=>1,'active'=>1),
            array('title' => 'SUPRA','brand_id'=>1,'active'=>1),
            array('title' => 'SURF','brand_id'=>1,'active'=>1),
            array('title' => 'TERCEL','brand_id'=>1,'active'=>1),
            array('title' => 'TOYOPET','brand_id'=>1,'active'=>1),
            array('title' => 'TUNNO','brand_id'=>1,'active'=>1),
            array('title' => 'VELLFIRE','brand_id'=>1,'active'=>1),
            array('title' => 'VENTURY','brand_id'=>1,'active'=>1),
            array('title' => 'VIOS','brand_id'=>1,'active'=>1),
            array('title' => 'VISTA','brand_id'=>1,'active'=>1),
            array('title' => 'VITZ','brand_id'=>1,'active'=>1),
            array('title' => 'VOLTZ','brand_id'=>1,'active'=>1),
            array('title' => 'VOXY','brand_id'=>1,'active'=>1),
            array('title' => 'WISH','brand_id'=>1,'active'=>1),
            array('title' => 'YARIS','brand_id'=>1,'active'=>1),
            array('title' => 'รุ่นอื่นๆ','brand_id'=>1,'active'=>1),

            array('title' => '600','brand_id'=>2,'active'=>1),
            array('title' => 'ACCORD','brand_id'=>2,'active'=>1),
            array('title' => 'ADANCIER','brand_id'=>2,'active'=>1),
            array('title' => 'AIRWAVE','brand_id'=>2,'active'=>1),
            array('title' => 'AMAZE','brand_id'=>2,'active'=>1),
            array('title' => 'ASCOT','brand_id'=>2,'active'=>1),
            array('title' => 'BRIO','brand_id'=>2,'active'=>1),
            array('title' => 'CITY','brand_id'=>2,'active'=>1),
            array('title' => 'CIVIC','brand_id'=>2,'active'=>1),
            array('title' => 'CR-V','brand_id'=>2,'active'=>1),
            array('title' => 'CRX','brand_id'=>2,'active'=>1),
            array('title' => 'DOMANI','brand_id'=>2,'active'=>1),
            array('title' => 'DUNK','brand_id'=>2,'active'=>1),
            array('title' => 'EDIX','brand_id'=>2,'active'=>1),
            array('title' => 'ELYSION','brand_id'=>2,'active'=>1),
            array('title' => 'FREED','brand_id'=>2,'active'=>1),
            array('title' => 'HR-V','brand_id'=>2,'active'=>1),
            array('title' => 'INSIGHT','brand_id'=>2,'active'=>1),
            array('title' => 'INSPIRE','brand_id'=>2,'active'=>1),
            array('title' => 'INTEGRA','brand_id'=>2,'active'=>1),
            array('title' => 'JAZZ','brand_id'=>2,'active'=>1),
            array('title' => 'LEGEND','brand_id'=>2,'active'=>1),
            array('title' => 'MOBILIO','brand_id'=>2,'active'=>1),
            array('title' => 'NSX','brand_id'=>2,'active'=>1),
            array('title' => 'ODYSSEY','brand_id'=>2,'active'=>1),
            array('title' => 'PRELUDE','brand_id'=>2,'active'=>1),
            array('title' => 'S2000','brand_id'=>2,'active'=>1),
            array('title' => 'STEPWGN','brand_id'=>2,'active'=>1),
            array('title' => 'STREAM','brand_id'=>2,'active'=>1),
            array('title' => 'TOURMASTER','brand_id'=>2,'active'=>1),
            array('title' => 'VIGOR','brand_id'=>2,'active'=>1),
            array('title' => 'รุ่นอื่นๆ','brand_id'=>2,'active'=>1),

            array('title' => '180 SX','brand_id'=>3,'active'=>1),
            array('title' => '200 SX','brand_id'=>3,'active'=>1),
            array('title' => '300 ZX','brand_id'=>3,'active'=>1),
            array('title' => '350Z','brand_id'=>3,'active'=>1),
            array('title' => '370Z','brand_id'=>3,'active'=>1),
            array('title' => 'Almera','brand_id'=>3,'active'=>1),
            array('title' => 'ATLAS','brand_id'=>3,'active'=>1),
            array('title' => 'IG-M','brand_id'=>3,'active'=>1),
            array('title' => 'BIG-M FRONTIER 1-2','brand_id'=>3,'active'=>1),
            array('title' => 'BIG-M FRONTIER NAVARA','brand_id'=>3,'active'=>1),
            array('title' => 'BLUEBIRD','brand_id'=>3,'active'=>1),
            array('title' => 'CARAVAN','brand_id'=>3,'active'=>1),
            array('title' => 'CEDRIC','brand_id'=>3,'active'=>1),
            array('title' => 'CEFIRO','brand_id'=>3,'active'=>1),
            array('title' => 'CIMA','brand_id'=>3,'active'=>1),
            array('title' => 'CUBE','brand_id'=>3,'active'=>1),
            array('title' => 'DATSUNS','brand_id'=>3,'active'=>1),
            array('title' => 'ELGRAND','brand_id'=>3,'active'=>1),
            array('title' => 'FAIRLADY','brand_id'=>3,'active'=>1),
            array('title' => 'FAIRLADY-Z','brand_id'=>3,'active'=>1),
            array('title' => 'FUGA','brand_id'=>3,'active'=>1),
            array('title' => 'GLORIA','brand_id'=>3,'active'=>1),
            array('title' => 'GTR','brand_id'=>3,'active'=>1),
            array('title' => 'INFINITI','brand_id'=>3,'active'=>1),
            array('title' => 'Juke','brand_id'=>3,'active'=>1),
            array('title' => 'LARGO','brand_id'=>3,'active'=>1),
            array('title' => 'LAUREL','brand_id'=>3,'active'=>1),
            array('title' => 'LEAF','brand_id'=>3,'active'=>1),
            array('title' => 'LEOPARD','brand_id'=>3,'active'=>1),
            array('title' => 'MARCH','brand_id'=>3,'active'=>1),
            array('title' => 'MAXIMA','brand_id'=>3,'active'=>1),
            array('title' => 'MURANO','brand_id'=>3,'active'=>1),
            array('title' => 'NP300','brand_id'=>3,'active'=>1),
            array('title' => 'NV','brand_id'=>3,'active'=>1),
            array('title' => 'NX','brand_id'=>3,'active'=>1),
            array('title' => 'PATROL','brand_id'=>3,'active'=>1),
            array('title' => 'PRAIRE','brand_id'=>3,'active'=>1),
            array('title' => 'PRESEA','brand_id'=>3,'active'=>1),
            array('title' => 'PRESIDENT','brand_id'=>3,'active'=>1),
            array('title' => 'PRIMERA','brand_id'=>3,'active'=>1),
            array('title' => 'PULSAR','brand_id'=>3,'active'=>1),
            array('title' => 'SAFARI','brand_id'=>3,'active'=>1),
            array('title' => 'SD','brand_id'=>3,'active'=>1),
            array('title' => 'SENTRA','brand_id'=>3,'active'=>1),
            array('title' => 'SERENA','brand_id'=>3,'active'=>1),
            array('title' => 'SILVIA','brand_id'=>3,'active'=>1),
            array('title' => 'SKYLINE','brand_id'=>3,'active'=>1),
            array('title' => 'STANZA','brand_id'=>3,'active'=>1),
            array('title' => 'SUNNY','brand_id'=>3,'active'=>1),
            array('title' => 'SYLPHY','brand_id'=>3,'active'=>1),
            array('title' => 'TEANA','brand_id'=>3,'active'=>1),
            array('title' => 'TERRANO','brand_id'=>3,'active'=>1),
            array('title' => 'TIIDA','brand_id'=>3,'active'=>1),
            array('title' => 'URVAN','brand_id'=>3,'active'=>1),
            array('title' => 'VANETTE','brand_id'=>3,'active'=>1),
            array('title' => 'VIOLET','brand_id'=>3,'active'=>1),
            array('title' => 'X-TRAIL','brand_id'=>3,'active'=>1),
            array('title' => 'รุ่นอื่นๆ','brand_id'=>3,'active'=>1),

            array('title' => '3000 GTO','brand_id'=>4,'active'=>1),
            array('title' => 'AEROBODY','brand_id'=>4,'active'=>1),
            array('title' => 'AIRTREK','brand_id'=>4,'active'=>1),
            array('title' => 'ASTRON','brand_id'=>4,'active'=>1),
            array('title' => 'ATTRAGE','brand_id'=>4,'active'=>1),
            array('title' => 'CHAMP','brand_id'=>4,'active'=>1),
            array('title' => 'COLT','brand_id'=>4,'active'=>1),
            array('title' => 'CYCLONE','brand_id'=>4,'active'=>1),
            array('title' => 'DELICA','brand_id'=>4,'active'=>1),
            array('title' => 'DIAMANTE','brand_id'=>4,'active'=>1),
            array('title' => 'ECLIPSE','brand_id'=>4,'active'=>1),
            array('title' => 'EVOLUTION','brand_id'=>4,'active'=>1),
            array('title' => 'FTO','brand_id'=>4,'active'=>1),
            array('title' => 'G-WAGON','brand_id'=>4,'active'=>1),
            array('title' => 'GALANT','brand_id'=>4,'active'=>1),
            array('title' => 'Jeep','brand_id'=>4,'active'=>1),
            array('title' => 'L200-CYCLONE','brand_id'=>4,'active'=>1),
            array('title' => 'L200-STRADA','brand_id'=>4,'active'=>1),
            array('title' => 'L300','brand_id'=>4,'active'=>1),
            array('title' => 'LANCER','brand_id'=>4,'active'=>1),
            array('title' => 'Mirage','brand_id'=>4,'active'=>1),
            array('title' => 'OUTLANDER','brand_id'=>4,'active'=>1),
            array('title' => 'PAJERO','brand_id'=>4,'active'=>1),
            array('title' => 'SPACE RUNNER','brand_id'=>4,'active'=>1),
            array('title' => 'SPACE WAGON','brand_id'=>4,'active'=>1),
            array('title' => 'STRADA G WAGON','brand_id'=>4,'active'=>1),
            array('title' => 'STRADA GRANDIS','brand_id'=>4,'active'=>1),
            array('title' => 'TRITON','brand_id'=>4,'active'=>1),
            array('title' => 'ULTIMA','brand_id'=>4,'active'=>1),
            array('title' => 'รุ่นอื่นๆ','brand_id'=>4,'active'=>1),

            array('title' => 'ASKA','brand_id'=>5,'active'=>1),
            array('title' => 'BUDDY','brand_id'=>5,'active'=>1),
            array('title' => 'CAB 4','brand_id'=>5,'active'=>1),
            array('title' => 'CAMEO','brand_id'=>5,'active'=>1),
            array('title' => 'D-MAX','brand_id'=>5,'active'=>1),
            array('title' => 'DRAGON EYE','brand_id'=>5,'active'=>1),
            array('title' => 'DRAGON POWER','brand_id'=>5,'active'=>1),
            array('title' => 'GEMINI','brand_id'=>5,'active'=>1),
            array('title' => 'GEO STORM','brand_id'=>5,'active'=>1),
            array('title' => 'HENO','brand_id'=>5,'active'=>1),
            array('title' => 'HI-LANDER','brand_id'=>5,'active'=>1),
            array('title' => 'IMPULSE','brand_id'=>5,'active'=>1),
            array('title' => 'KB ปี 84-90','brand_id'=>5,'active'=>1),
            array('title' => 'MU','brand_id'=>5,'active'=>1),
            array('title' => 'MU-7','brand_id'=>5,'active'=>1),
            array('title' => 'RODEO','brand_id'=>5,'active'=>1),
            array('title' => 'SPACECAB','brand_id'=>5,'active'=>1),
            array('title' => 'SPARK EX','brand_id'=>5,'active'=>1),
            array('title' => 'SUPREME','brand_id'=>5,'active'=>1),
            array('title' => 'TFR ปี 91-97','brand_id'=>5,'active'=>1),
            array('title' => 'TROOPER','brand_id'=>5,'active'=>1),
            array('title' => 'V-CROSS','brand_id'=>5,'active'=>1),
            array('title' => 'VEGA','brand_id'=>5,'active'=>1),
            array('title' => 'VERTEX','brand_id'=>5,'active'=>1),
            array('title' => 'รุ่นอื่นๆ','brand_id'=>5,'active'=>1),

            array('title' => '190','brand_id'=>6,'active'=>1),
            array('title' => '200','brand_id'=>6,'active'=>1),
            array('title' => '212','brand_id'=>6,'active'=>1),
            array('title' => '220','brand_id'=>6,'active'=>1),
            array('title' => '230','brand_id'=>6,'active'=>1),
            array('title' => '240','brand_id'=>6,'active'=>1),
            array('title' => '250','brand_id'=>6,'active'=>1),
            array('title' => '280','brand_id'=>6,'active'=>1),
            array('title' => '300','brand_id'=>6,'active'=>1),
            array('title' => '350','brand_id'=>6,'active'=>1),
            array('title' => '380','brand_id'=>6,'active'=>1),
            array('title' => '400','brand_id'=>6,'active'=>1),
            array('title' => '450','brand_id'=>6,'active'=>1),
            array('title' => '500','brand_id'=>6,'active'=>1),
            array('title' => '560','brand_id'=>6,'active'=>1),
            array('title' => '600','brand_id'=>6,'active'=>1),
            array('title' => 'A-CLASS','brand_id'=>6,'active'=>1),
            array('title' => 'B-CLASS','brand_id'=>6,'active'=>1),
            array('title' => 'C-CLASS','brand_id'=>6,'active'=>1),
            array('title' => 'CL-CLASS','brand_id'=>6,'active'=>1),
            array('title' => 'CLK-CLASS','brand_id'=>6,'active'=>1),
            array('title' => 'CLS-CLASS','brand_id'=>6,'active'=>1),
            array('title' => 'E-CLASS','brand_id'=>6,'active'=>1),
            array('title' => 'G-CLASS','brand_id'=>6,'active'=>1),
            array('title' => 'MB-CLASS','brand_id'=>6,'active'=>1),
            array('title' => 'ML-CLASS','brand_id'=>6,'active'=>1),
            array('title' => 'R-CLAS','brand_id'=>6,'active'=>1),
            array('title' => 'S-CLASS','brand_id'=>6,'active'=>1),
            array('title' => 'SL-CLASS','brand_id'=>6,'active'=>1),
            array('title' => 'SLK-CLASS','brand_id'=>6,'active'=>1),
            array('title' => 'SMART','brand_id'=>6,'active'=>1),
            array('title' => 'V-CLASS','brand_id'=>6,'active'=>1),
            array('title' => 'VITO','brand_id'=>6,'active'=>1),
            array('title' => 'รุ่นอื่นๆ','brand_id'=>6,'active'=>1),

            array('title' => 'Classic-Car','brand_id'=>7,'active'=>1),
            array('title' => 'L7','brand_id'=>7,'active'=>1),
            array('title' => 'M3','brand_id'=>7,'active'=>1),
            array('title' => 'M5','brand_id'=>7,'active'=>1),
            array('title' => 'M6','brand_id'=>7,'active'=>1),
            array('title' => 'MINI','brand_id'=>7,'active'=>1),
            array('title' => 'SERIES 1','brand_id'=>7,'active'=>1),
            array('title' => 'SERIES 3','brand_id'=>7,'active'=>1),
            array('title' => 'SERIES 5','brand_id'=>7,'active'=>1),
            array('title' => 'SERIES 6','brand_id'=>7,'active'=>1),
            array('title' => 'SERIES 7','brand_id'=>7,'active'=>1),
            array('title' => 'SERIES 8','brand_id'=>7,'active'=>1),
            array('title' => 'X1','brand_id'=>7,'active'=>1),
            array('title' => 'X2','brand_id'=>7,'active'=>1),
            array('title' => 'X3','brand_id'=>7,'active'=>1),
            array('title' => 'X4','brand_id'=>7,'active'=>1),
            array('title' => 'X5','brand_id'=>7,'active'=>1),
            array('title' => 'X6','brand_id'=>7,'active'=>1),
            array('title' => 'Z3','brand_id'=>7,'active'=>1),
            array('title' => 'Z4','brand_id'=>7,'active'=>1),
            array('title' => 'รุ่นอื่นๆ','brand_id'=>7,'active'=>1),

            array('title' => '121','brand_id'=>8,'active'=>1),
            array('title' => '323','brand_id'=>8,'active'=>1),
            array('title' => '323-ASTINA','brand_id'=>8,'active'=>1),
            array('title' => '626','brand_id'=>8,'active'=>1),
            array('title' => '808','brand_id'=>8,'active'=>1),
            array('title' => '929','brand_id'=>8,'active'=>1),
            array('title' => 'B2000','brand_id'=>8,'active'=>1),
            array('title' => 'B2500','brand_id'=>8,'active'=>1),
            array('title' => 'BT-50','brand_id'=>8,'active'=>1),
            array('title' => 'CAPELLA','brand_id'=>8,'active'=>1),
            array('title' => 'CRONOS','brand_id'=>8,'active'=>1),
            array('title' => 'CX-7','brand_id'=>8,'active'=>1),
            array('title' => 'FAMILI','brand_id'=>8,'active'=>1),
            array('title' => 'FAMILIA COUPE','brand_id'=>8,'active'=>1),
            array('title' => 'FIGHTER','brand_id'=>8,'active'=>1),
            array('title' => 'LANTIS','brand_id'=>8,'active'=>1),
            array('title' => 'MARATHON','brand_id'=>8,'active'=>1),
            array('title' => 'MAXNUM','brand_id'=>8,'active'=>1),
            array('title' => 'MAZDA 2 elegance','brand_id'=>8,'active'=>1),
            array('title' => 'MAZDA 2 sport','brand_id'=>8,'active'=>1),
            array('title' => 'MAZDA 3','brand_id'=>8,'active'=>1),
            array('title' => 'MAZDA 5','brand_id'=>8,'active'=>1),
            array('title' => 'MAZDA 6','brand_id'=>8,'active'=>1),
            array('title' => 'MPV','brand_id'=>8,'active'=>1),
            array('title' => 'MX5','brand_id'=>8,'active'=>1),
            array('title' => 'RX3','brand_id'=>8,'active'=>1),
            array('title' => 'RX7','brand_id'=>8,'active'=>1),
            array('title' => 'RX8','brand_id'=>8,'active'=>1),
            array('title' => 'THUNDER','brand_id'=>8,'active'=>1),
            array('title' => 'TRIBUTE','brand_id'=>8,'active'=>1),
            array('title' => 'XEDOS 9','brand_id'=>8,'active'=>1),
            array('title' => 'รุ่นอื่นๆ','brand_id'=>8,'active'=>1),

            array('title' => 'ASPIRE','brand_id'=>9,'active'=>1),
            array('title' => 'CADILAC HEETWOOD','brand_id'=>9,'active'=>1),
            array('title' => 'CAPRI','brand_id'=>9,'active'=>1),
            array('title' => 'CORTINA','brand_id'=>9,'active'=>1),
            array('title' => 'Ecosport','brand_id'=>9,'active'=>1),
            array('title' => 'ESCAPE','brand_id'=>9,'active'=>1),
            array('title' => 'EVEREST','brand_id'=>9,'active'=>1),
            array('title' => 'EXPLORER','brand_id'=>9,'active'=>1),
            array('title' => 'FALCON','brand_id'=>9,'active'=>1),
            array('title' => 'FESTIVA','brand_id'=>9,'active'=>1),
            array('title' => 'FIESTA','brand_id'=>9,'active'=>1),
            array('title' => 'FOCUS','brand_id'=>9,'active'=>1),
            array('title' => 'GT','brand_id'=>9,'active'=>1),
            array('title' => 'LASER','brand_id'=>9,'active'=>1),
            array('title' => 'LINCOLN','brand_id'=>9,'active'=>1),
            array('title' => 'MARATHON','brand_id'=>9,'active'=>1),
            array('title' => 'MONDEO','brand_id'=>9,'active'=>1),
            array('title' => 'MUSTANG','brand_id'=>9,'active'=>1),
            array('title' => 'RANGER','brand_id'=>9,'active'=>1),
            array('title' => 'SIERRA','brand_id'=>9,'active'=>1),
            array('title' => 'TELSTAR','brand_id'=>9,'active'=>1),
            array('title' => 'TERRITORY','brand_id'=>9,'active'=>1),
            array('title' => 'THUNDERBIRD','brand_id'=>9,'active'=>1),

            array('title' => 'ALLROADER','brand_id'=>10,'active'=>1),
            array('title' => 'ASTRO','brand_id'=>10,'active'=>1),
            array('title' => 'AVEO','brand_id'=>10,'active'=>1),
            array('title' => 'CAMARO','brand_id'=>10,'active'=>1),
            array('title' => 'CAPTIVA','brand_id'=>10,'active'=>1),
            array('title' => 'CHEVY VAN','brand_id'=>10,'active'=>1),
            array('title' => 'COLORADO','brand_id'=>10,'active'=>1),
            array('title' => 'CORVETTE','brand_id'=>10,'active'=>1),
            array('title' => 'CRUZE','brand_id'=>10,'active'=>1),
            array('title' => 'EXPRESS','brand_id'=>10,'active'=>1),
            array('title' => 'IMPALA','brand_id'=>10,'active'=>1),
            array('title' => 'LUMINA','brand_id'=>10,'active'=>1),
            array('title' => 'OPTR','brand_id'=>10,'active'=>1),
            array('title' => 'S10','brand_id'=>10,'active'=>1),
            array('title' => 'SAVANA','brand_id'=>10,'active'=>1),
            array('title' => 'SONIC','brand_id'=>10,'active'=>1),
            array('title' => 'SPIN','brand_id'=>10,'active'=>1),
            array('title' => 'TRAILBLAZER','brand_id'=>10,'active'=>1),
            array('title' => 'ZAFIRA','brand_id'=>10,'active'=>1),

            array('title' => '440','brand_id'=>11,'active'=>1),
            array('title' => '460','brand_id'=>11,'active'=>1),
            array('title' => '480','brand_id'=>11,'active'=>1),
            array('title' => '740','brand_id'=>11,'active'=>1),
            array('title' => '850','brand_id'=>11,'active'=>1),
            array('title' => '940','brand_id'=>11,'active'=>1),
            array('title' => '960','brand_id'=>11,'active'=>1),
            array('title' => 'C30','brand_id'=>11,'active'=>1),
            array('title' => 'C70','brand_id'=>11,'active'=>1),
            array('title' => 'CLASSIC CAR','brand_id'=>11,'active'=>1),
            array('title' => 'S40','brand_id'=>11,'active'=>1),
            array('title' => 'S60','brand_id'=>11,'active'=>1),
            array('title' => 'S70','brand_id'=>11,'active'=>1),
            array('title' => 'S80','brand_id'=>11,'active'=>1),
            array('title' => 'S90','brand_id'=>11,'active'=>1),
            array('title' => 'V40','brand_id'=>11,'active'=>1),
            array('title' => 'V50','brand_id'=>11,'active'=>1),
            array('title' => 'V70','brand_id'=>11,'active'=>1),
            array('title' => 'XC70','brand_id'=>11,'active'=>1),
            array('title' => 'XC90','brand_id'=>11,'active'=>1),

            array('title' => 'ALFA ROMEO 155','brand_id'=>12,'active'=>1),
            array('title' => 'ALFA ROMEO 156','brand_id'=>12,'active'=>1),
            array('title' => 'ALFA ROMEO 166','brand_id'=>12,'active'=>1),
            array('title' => 'ALFA ROMEO 1750','brand_id'=>12,'active'=>1),
            array('title' => 'GIULIETTA','brand_id'=>12,'active'=>1),
            array('title' => 'GT','brand_id'=>12,'active'=>1),
            array('title' => 'GTV','brand_id'=>12,'active'=>1),
            array('title' => 'SPIDER','brand_id'=>12,'active'=>1),
            array('title' => 'SPIDER 2000','brand_id'=>12,'active'=>1),

            array('title' => 'CYGNET','brand_id'=>13,'active'=>1),
            array('title' => 'DB 7 VANTAGE','brand_id'=>13,'active'=>1),
            array('title' => 'DB 9','brand_id'=>13,'active'=>1),
            array('title' => 'RAPIDE','brand_id'=>13,'active'=>1),
            array('title' => 'V12 VANTAGE','brand_id'=>13,'active'=>1),
            array('title' => 'V8 VANTAGE','brand_id'=>13,'active'=>1),
            array('title' => 'VANTAGE S','brand_id'=>13,'active'=>1),
            array('title' => 'VIRAGE','brand_id'=>13,'active'=>1),

            array('title' => '100','brand_id'=>14,'active'=>1),
            array('title' => '80','brand_id'=>14,'active'=>1),
            array('title' => 'A1','brand_id'=>14,'active'=>1),
            array('title' => 'A3','brand_id'=>14,'active'=>1),
            array('title' => 'A4','brand_id'=>14,'active'=>1),
            array('title' => 'A5','brand_id'=>14,'active'=>1),
            array('title' => 'A6','brand_id'=>14,'active'=>1),
            array('title' => 'A7','brand_id'=>14,'active'=>1),
            array('title' => 'A8','brand_id'=>14,'active'=>1),
            array('title' => 'Q3','brand_id'=>14,'active'=>1),
            array('title' => 'Q5','brand_id'=>14,'active'=>1),
            array('title' => 'Q7','brand_id'=>14,'active'=>1),
            array('title' => 'R8','brand_id'=>14,'active'=>1),
            array('title' => 'RS3','brand_id'=>14,'active'=>1),
            array('title' => 'RS5','brand_id'=>14,'active'=>1),
            array('title' => 'RS6','brand_id'=>14,'active'=>1),
            array('title' => 'S3','brand_id'=>14,'active'=>1),
            array('title' => 'S4','brand_id'=>14,'active'=>1),
            array('title' => 'S5','brand_id'=>14,'active'=>1),
            array('title' => 'S6','brand_id'=>14,'active'=>1),
            array('title' => 'TT','brand_id'=>14,'active'=>1),
            array('title' => 'TT RS','brand_id'=>14,'active'=>1),
            array('title' => 'TTS','brand_id'=>14,'active'=>1),

            array('title' => 'FX4','brand_id'=>15,'active'=>1),

            array('title' => 'ARNAGE','brand_id'=>16,'active'=>1),
            array('title' => 'BROOKLANDS','brand_id'=>16,'active'=>1),
            array('title' => 'CONTINENTAL','brand_id'=>16,'active'=>1),
            array('title' => 'FLYING SPUR','brand_id'=>16,'active'=>1),
            array('title' => 'TURBO','brand_id'=>16,'active'=>1),

            array('title' => 'CTS-V','brand_id'=>17,'active'=>1),
            array('title' => 'ELDORADO','brand_id'=>17,'active'=>1),
            array('title' => 'ESCALADE','brand_id'=>17,'active'=>1),
            array('title' => 'FLEETWOOD','brand_id'=>17,'active'=>1),
            array('title' => 'SEDAN DEVILLE','brand_id'=>17,'active'=>1),
            array('title' => 'SEVILLE','brand_id'=>17,'active'=>1),
            array('title' => 'STS','brand_id'=>17,'active'=>1),

            array('title' => '300C','brand_id'=>18,'active'=>1),
            array('title' => '300M','brand_id'=>18,'active'=>1),
            array('title' => 'NEON','brand_id'=>18,'active'=>1),
            array('title' => 'PT CRUISER','brand_id'=>18,'active'=>1),
            array('title' => 'VOYAGER','brand_id'=>18,'active'=>1),

            array('title' => 'AX','brand_id'=>19,'active'=>1),
            array('title' => 'Berlingo','brand_id'=>19,'active'=>1),
            array('title' => 'C5','brand_id'=>19,'active'=>1),
            array('title' => 'C8','brand_id'=>19,'active'=>1),
            array('title' => 'CX20','brand_id'=>19,'active'=>1),
            array('title' => 'DS3','brand_id'=>19,'active'=>1),
            array('title' => 'JUMPER','brand_id'=>19,'active'=>1),
            array('title' => 'XANTIA','brand_id'=>19,'active'=>1),
            array('title' => 'XSARA','brand_id'=>19,'active'=>1),

            array('title' => 'ESPERO','brand_id'=>20,'active'=>1),
            array('title' => 'NEXIA','brand_id'=>20,'active'=>1),

            array('title' => 'ATRAI','brand_id'=>21,'active'=>1),
            array('title' => 'ATRAI WAGON','brand_id'=>21,'active'=>1),
            array('title' => 'COPEN','brand_id'=>21,'active'=>1),
            array('title' => 'HIJET','brand_id'=>21,'active'=>1),
            array('title' => 'MIDGET II','brand_id'=>21,'active'=>1),
            array('title' => 'MIRA','brand_id'=>21,'active'=>1),
            array('title' => 'MOVE','brand_id'=>21,'active'=>1),
            array('title' => 'OPTI','brand_id'=>21,'active'=>1),
            array('title' => 'TERIOS','brand_id'=>21,'active'=>1),
            array('title' => 'YRV','brand_id'=>21,'active'=>1),

            array('title' => 'MINI TRUCK','brand_id'=>22,'active'=>1),
            array('title' => 'MINI VAN','brand_id'=>22,'active'=>1),
            array('title' => 'V27','brand_id'=>22,'active'=>1),

            array('title' => '360 MODENA','brand_id'=>23,'active'=>1),
            array('title' => '360 SPIDER','brand_id'=>23,'active'=>1),
            array('title' => '360 STRADALE','brand_id'=>23,'active'=>1),
            array('title' => '365 DAYTONA','brand_id'=>23,'active'=>1),
            array('title' => '430 SCUDERIA','brand_id'=>23,'active'=>1),
            array('title' => '458 ITALIA ','brand_id'=>23,'active'=>1),
            array('title' => '512 TR','brand_id'=>23,'active'=>1),
            array('title' => '575M MARANELLO','brand_id'=>23,'active'=>1),
            array('title' => '599 GTB','brand_id'=>23,'active'=>1),
            array('title' => '612 SCAGLIETTI','brand_id'=>23,'active'=>1),
            array('title' => 'CALIFORNIA','brand_id'=>23,'active'=>1),
            array('title' => 'F355 BERLINITTA','brand_id'=>23,'active'=>1),
            array('title' => 'F430','brand_id'=>23,'active'=>1),
            array('title' => 'F430 CHALLENGE','brand_id'=>23,'active'=>1),
            array('title' => 'F430 SPIDER','brand_id'=>23,'active'=>1),
            array('title' => 'FERRARI 348','brand_id'=>23,'active'=>1),

            array('title' => '695 FERRARI','brand_id'=>24,'active'=>1),
            array('title' => 'FIAT 1100','brand_id'=>24,'active'=>1),
            array('title' => 'FIAT 13','brand_id'=>24,'active'=>1),
            array('title' => 'FIAT 1500','brand_id'=>24,'active'=>1),
            array('title' => 'FIAT 500','brand_id'=>24,'active'=>1),
            array('title' => 'PUNTO','brand_id'=>24,'active'=>1),

            array('title' => 'SAVANA','brand_id'=>25,'active'=>1),

            array('title' => 'HUMMER H2','brand_id'=>26,'active'=>1),
            array('title' => 'HUMMER H3','brand_id'=>26,'active'=>1),

            array('title' => 'ACCENT','brand_id'=>27,'active'=>1),
            array('title' => 'ELANTRA','brand_id'=>27,'active'=>1),
            array('title' => 'EXCEL','brand_id'=>27,'active'=>1),
            array('title' => 'GRAND STAREX','brand_id'=>27,'active'=>1),
            array('title' => 'H-1','brand_id'=>27,'active'=>1),
            array('title' => 'SONATA','brand_id'=>27,'active'=>1),
            array('title' => 'SPRINT','brand_id'=>27,'active'=>1),
            array('title' => 'TIBURON','brand_id'=>27,'active'=>1),
            array('title' => 'TUCSON','brand_id'=>27,'active'=>1),

            array('title' => 'DAIMLER','brand_id'=>28,'active'=>1),
            array('title' => 'MK2','brand_id'=>28,'active'=>1),
            array('title' => 'S-TYPE','brand_id'=>28,'active'=>1),
            array('title' => 'OVEREIGN','brand_id'=>28,'active'=>1),
            array('title' => 'X-TYPE','brand_id'=>28,'active'=>1),
            array('title' => 'XF-SERIES','brand_id'=>28,'active'=>1),
            array('title' => 'XJ-SERIES','brand_id'=>28,'active'=>1),
            array('title' => 'XJL-SERIES','brand_id'=>28,'active'=>1),
            array('title' => 'XJR','brand_id'=>28,'active'=>1),
            array('title' => 'XK-SERIES','brand_id'=>28,'active'=>1),
            array('title' => 'XK140','brand_id'=>28,'active'=>1),
            array('title' => 'XKR','brand_id'=>28,'active'=>1),

            array('title' => 'CHEROKEE','brand_id'=>29,'active'=>1),
            array('title' => 'GRAND CHEROKEE','brand_id'=>29,'active'=>1),
            array('title' => 'WILLY','brand_id'=>29,'active'=>1),
            array('title' => 'WRANGLER','brand_id'=>29,'active'=>1),

            array('title' => 'CARENS','brand_id'=>30,'active'=>1),
            array('title' => 'CARNIVAL','brand_id'=>30,'active'=>1),
            array('title' => 'GRAND CARNIVAL','brand_id'=>30,'active'=>1),
            array('title' => 'GRAND SPORTAGE','brand_id'=>30,'active'=>1),
            array('title' => 'UMBO','brand_id'=>30,'active'=>1),
            array('title' => 'PICANT','brand_id'=>30,'active'=>1),
            array('title' => 'PREGIO','brand_id'=>30,'active'=>1),
            array('title' => 'SORENTO','brand_id'=>30,'active'=>1),
            array('title' => 'SOUL','brand_id'=>30,'active'=>1),
            array('title' => 'SPORTAGE','brand_id'=>30,'active'=>1),

            array('title' => 'AVENTADOR','brand_id'=>31,'active'=>1),
            array('title' => 'DIABIO','brand_id'=>31,'active'=>1),
            array('title' => 'GALLARDO','brand_id'=>31,'active'=>1),
            array('title' => 'MURCIELAGO','brand_id'=>31,'active'=>1),

            array('title' => 'BETA','brand_id'=>32,'active'=>1),

            array('title' => 'DEFENDER','brand_id'=>33,'active'=>1),
            array('title' => 'DISCOVERY','brand_id'=>33,'active'=>1),
            array('title' => 'FREELANDER','brand_id'=>33,'active'=>1),
            array('title' => 'RANGE ROVER','brand_id'=>33,'active'=>1),
            array('title' => 'SERIES 1','brand_id'=>33,'active'=>1),

            array('title' => 'ARISTO','brand_id'=>34,'active'=>1),
            array('title' => 'CT200h','brand_id'=>34,'active'=>1),
            array('title' => 'ES300','brand_id'=>34,'active'=>1),
            array('title' => 'GS250','brand_id'=>34,'active'=>1),
            array('title' => 'GS300','brand_id'=>34,'active'=>1),
            array('title' => 'GS350','brand_id'=>34,'active'=>1),
            array('title' => 'IS F','brand_id'=>34,'active'=>1),
            array('title' => 'IS200','brand_id'=>34,'active'=>1),
            array('title' => 'IS250','brand_id'=>34,'active'=>1),
            array('title' => 'IS250C','brand_id'=>34,'active'=>1),
            array('title' => 'LS400','brand_id'=>34,'active'=>1),
            array('title' => 'LS430','brand_id'=>34,'active'=>1),
            array('title' => 'LS460','brand_id'=>34,'active'=>1),
            array('title' => 'LS460L','brand_id'=>34,'active'=>1),
            array('title' => 'LS600hl','brand_id'=>34,'active'=>1),
            array('title' => 'LX460','brand_id'=>34,'active'=>1),
            array('title' => 'LX470 CYGNUS','brand_id'=>34,'active'=>1),
            array('title' => 'LX570','brand_id'=>34,'active'=>1),
            array('title' => 'Nx300h','brand_id'=>34,'active'=>1),
            array('title' => 'X270','brand_id'=>34,'active'=>1),
            array('title' => 'RX300','brand_id'=>34,'active'=>1),
            array('title' => 'RX330','brand_id'=>34,'active'=>1),
            array('title' => 'RX350','brand_id'=>34,'active'=>1),
            array('title' => 'RX450h','brand_id'=>34,'active'=>1),
            array('title' => 'SC430','brand_id'=>34,'active'=>1),
            array('title' => 'SOARER','brand_id'=>34,'active'=>1),

            array('title' => 'ELISE','brand_id'=>35,'active'=>1),
            array('title' => 'ESPRIT','brand_id'=>35,'active'=>1),
            array('title' => 'EVORA','brand_id'=>35,'active'=>1),
            array('title' => 'EXIGE','brand_id'=>35,'active'=>1),
            array('title' => 'SPORT','brand_id'=>35,'active'=>1),

            array('title' => 'GHIBLI','brand_id'=>36,'active'=>1),
            array('title' => 'GRANTURISMO','brand_id'=>36,'active'=>1),
            array('title' => 'GT COUPE','brand_id'=>36,'active'=>1),
            array('title' => 'QUATTROPORTE','brand_id'=>36,'active'=>1),
            array('title' => 'SPYDER','brand_id'=>36,'active'=>1),

            array('title' => 'MGB','brand_id'=>37,'active'=>1),
            array('title' => 'MGF','brand_id'=>37,'active'=>1),
            array('title' => 'MIDGET MARK','brand_id'=>37,'active'=>1),

            array('title' => 'AUSTIN Classic','brand_id'=>38,'active'=>1),
            array('title' => 'AUSTIN MINI','brand_id'=>38,'active'=>1),
            array('title' => 'COOPER','brand_id'=>38,'active'=>1),
            array('title' => 'ONE','brand_id'=>38,'active'=>1),

            array('title' => 'ASTRA','brand_id'=>39,'active'=>1),
            array('title' => 'CALIBRA','brand_id'=>39,'active'=>1),
            array('title' => 'COMMODORE','brand_id'=>39,'active'=>1),
            array('title' => 'CORSA','brand_id'=>39,'active'=>1),
            array('title' => 'KAPITAN','brand_id'=>39,'active'=>1),
            array('title' => 'OMEGA','brand_id'=>39,'active'=>1),
            array('title' => 'VECTRA','brand_id'=>39,'active'=>1),

            array('title' => 'BIPPER','brand_id'=>40,'active'=>1),
            array('title' => 'PARTNER','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 1007','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 205','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 206','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 207','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 305','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 306','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 307','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 308','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 405','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 406','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 407','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 504','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 505','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 605','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 607','brand_id'=>40,'active'=>1),
            array('title' => 'PEUGEOT 807','brand_id'=>40,'active'=>1),
            array('title' => 'RCZ','brand_id'=>40,'active'=>1),

            array('title' => '911 CARRERA','brand_id'=>41,'active'=>1),
            array('title' => '911 CARRERA S','brand_id'=>41,'active'=>1),
            array('title' => '911 CARRERA 4','brand_id'=>41,'active'=>1),
            array('title' => '911 GT2','brand_id'=>41,'active'=>1),
            array('title' => '911 SPORT Classic','brand_id'=>41,'active'=>1),
            array('title' => '911 TARGA 4S','brand_id'=>41,'active'=>1),
            array('title' => '911 TURBO','brand_id'=>41,'active'=>1),
            array('title' => '928','brand_id'=>41,'active'=>1),
            array('title' => '993 CARRERA','brand_id'=>41,'active'=>1),
            array('title' => '993 TARGA','brand_id'=>41,'active'=>1),
            array('title' => '996 CARRERA','brand_id'=>41,'active'=>1),
            array('title' => '996 GT3','brand_id'=>41,'active'=>1),
            array('title' => '997 CARRERA','brand_id'=>41,'active'=>1),
            array('title' => 'BOXSTER','brand_id'=>41,'active'=>1),
            array('title' => 'CARRERA','brand_id'=>41,'active'=>1),
            array('title' => 'CAYENNE','brand_id'=>41,'active'=>1),
            array('title' => 'CAYMAN','brand_id'=>41,'active'=>1),
            array('title' => 'PANAMERA','brand_id'=>41,'active'=>1),

            array('title' => 'EXORA','brand_id'=>42,'active'=>1),
            array('title' => 'GEN2','brand_id'=>42,'active'=>1),
            array('title' => 'NEO','brand_id'=>42,'active'=>1),
            array('title' => 'PERSONA','brand_id'=>42,'active'=>1),
            array('title' => 'SAGA','brand_id'=>42,'active'=>1),
            array('title' => 'SATRIA','brand_id'=>42,'active'=>1),
            array('title' => 'SAVVY','brand_id'=>42,'active'=>1),
            array('title' => 'WAJA','brand_id'=>42,'active'=>1),

            array('title' => 'R-19','brand_id'=>43,'active'=>1),

            array('title' => 'CORNICHE II','brand_id'=>44,'active'=>1),
            array('title' => 'GHOST','brand_id'=>44,'active'=>1),
            array('title' => 'PHANTOM','brand_id'=>44,'active'=>1),
            array('title' => 'SILVER SHADOW II','brand_id'=>44,'active'=>1),
            array('title' => 'SILVER SPIRIT II','brand_id'=>44,'active'=>1),
            array('title' => 'SILVER SPUR II','brand_id'=>44,'active'=>1),
            array('title' => 'SILVER SPUR III','brand_id'=>44,'active'=>1),

            array('title' => '220 COUPE','brand_id'=>45,'active'=>1),
            array('title' => '623','brand_id'=>45,'active'=>1),
            array('title' => '75','brand_id'=>45,'active'=>1),
            array('title' => '827 STERLING','brand_id'=>45,'active'=>1),
            array('title' => 'MINI','brand_id'=>45,'active'=>1),

            array('title' => '9-5','brand_id'=>46,'active'=>1),
            array('title' => '900','brand_id'=>46,'active'=>1),
            array('title' => '9000','brand_id'=>46,'active'=>1),

            array('title' => 'FABIA','brand_id'=>47,'active'=>1),
            array('title' => 'OCTAVIA','brand_id'=>47,'active'=>1),

            array('title' => 'SMART','brand_id'=>48,'active'=>1),

            array('title' => 'ACTYON','brand_id'=>49,'active'=>1),
            array('title' => 'CHAIRMAN','brand_id'=>49,'active'=>1),
            array('title' => 'KYRON','brand_id'=>49,'active'=>1),
            array('title' => 'MUSSO','brand_id'=>49,'active'=>1),
            array('title' => 'REXTON','brand_id'=>49,'active'=>1),
            array('title' => 'STAVIC','brand_id'=>49,'active'=>1),

            array('title' => 'BRZ','brand_id'=>50,'active'=>1),
            array('title' => 'FORESTER','brand_id'=>50,'active'=>1),
            array('title' => 'GLT','brand_id'=>50,'active'=>1),
            array('title' => 'IMPREZA','brand_id'=>50,'active'=>1),
            array('title' => 'LEGACY','brand_id'=>50,'active'=>1),
            array('title' => 'OUTBACK','brand_id'=>50,'active'=>1),
            array('title' => 'R2','brand_id'=>50,'active'=>1),
            array('title' => 'Xv','brand_id'=>50,'active'=>1),

            array('title' => 'ALTO','brand_id'=>51,'active'=>1),
            array('title' => 'APV','brand_id'=>51,'active'=>1),
            array('title' => 'CAPPUCCINO','brand_id'=>51,'active'=>1),
            array('title' => 'CARIBIAN','brand_id'=>51,'active'=>1),
            array('title' => 'CARRY','brand_id'=>51,'active'=>1),
            array('title' => 'Celerio','brand_id'=>51,'active'=>1),
            array('title' => 'CERVO','brand_id'=>51,'active'=>1),
            array('title' => 'ERTIGA','brand_id'=>51,'active'=>1),
            array('title' => 'ESTEEM','brand_id'=>51,'active'=>1),
            array('title' => 'GRAND VITARA','brand_id'=>51,'active'=>1),
            array('title' => 'JIMNY','brand_id'=>51,'active'=>1),
            array('title' => 'SWIFT','brand_id'=>51,'active'=>1),
            array('title' => 'VITARA','brand_id'=>51,'active'=>1),
            array('title' => 'WAGON R','brand_id'=>51,'active'=>1),
            array('title' => 'WAGON R PLUS','brand_id'=>51,'active'=>1),

            array('title' => 'MODEL-S','brand_id'=>52,'active'=>1),

            array('title' => 'BEETLE','brand_id'=>53,'active'=>1),
            array('title' => 'CARAVELLE','brand_id'=>53,'active'=>1),
            array('title' => 'CLASSIC CAR','brand_id'=>53,'active'=>1),
            array('title' => 'CORRADO','brand_id'=>53,'active'=>1),
            array('title' => 'GOLF','brand_id'=>53,'active'=>1),
            array('title' => 'NEW BEETLE','brand_id'=>53,'active'=>1),
            array('title' => 'PASSAT','brand_id'=>53,'active'=>1),
            array('title' => 'POLO','brand_id'=>53,'active'=>1),
            array('title' => 'SCIROCCO','brand_id'=>53,'active'=>1),
            array('title' => 'SHARAN','brand_id'=>53,'active'=>1),
            array('title' => 'TOUAREG','brand_id'=>53,'active'=>1),
            array('title' => 'TRANSPORTER','brand_id'=>53,'active'=>1),
            array('title' => 'VENTO','brand_id'=>53,'active'=>1),

        ));
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('models');
    }
}
